### ISSUE TITLE
Allow for OSC / Control Characters

### ISSUE THREAD

**Issue by dsully** [Nukesor/comfy-table#137]
### A detailed description of the feature you would like to see added.

Hi - I'd like to include OSC-8 hyperlinks in various columns - unfortunately that causes the column (and table) width to be incorrectly calculated.

### Explain your usecase of the requested feature

See above.

Here's an example OSC-8 sequence:

```shell
printf '\033]8;;https://github.com\033\\This is a link\033]8;;\033\\\n'
```

**Comment by Nukesor** [comment]
Comfy-table has gained support for this behavior via a community contribution.
From my knowledge, that functionality is stable but not yet widely battle-tested.

Since this has been asked for multiple times, I moved the detailed feature-flag documentation from the `Cargo.toml` to the the README :)

Could you check whether this answers your question and whether you would have found it? I'm not sure where best to place feature flag documentation, as there's sadly no real support for it in the rust ecosystem yet.

https://github.com/Nukesor/comfy-table/blob/ea2c1391d23d8f5357d2885b741c92a080672de9/README.md

**Comment by Nukesor** [comment]
Also, if you're interested, It would be awesome if somebody that actually uses this wrote some property tests for this feature :D  

Theres a huge amount of possible edge-cases when splitting ansi escape sequences and I really would like to see more test coverage on this :)

**Comment by Nukesor** [comment]
ping @dsully

**Comment by dsully** [comment]
Heya - I assume the feature is `custom_styling`? I've not had a chance to try this yet. Hopefully today or tomorrow.

**Comment by dsully** [comment]
So this kind of works:

![CleanShot 2024-04-01 at 19 15 25@2x](https://github.com/Nukesor/comfy-table/assets/22371/ab153fa3-3be6-422f-a6d4-5fb56dbb36eb)

The cell the OSC-8 escape codes are in are properly sized, but the header cell is not.

Any thoughts here?

**Comment by Nukesor** [comment]
Ook.

Since I didn't write this and have never used this, I didn't know the full capabilities of that logic. It seems that there's support for ANSI escape sequences but there hasn't been any logic for OSC sequences.

Would you mind investigating and extending that logic? All current logic is gated behind the `custom_styling` feature flag, so it should be at least somewhat easy to find the logic thet needs to be extended :)

Original ANSI issue:
https://github.com/Nukesor/comfy-table/pull/77

**Comment by dsully** [comment]
I looked at it a bit yesterday. I'll try and find time this week to dig deeper.

Is the cell width calculator behind that flag as well?

**Comment by Nukesor** [comment]
Yep. That should be the `measure_text_width` function, which is in `content_split/{custom_styling.mod,normal.rs}`

**Comment by dsully** [comment]
PR above. `console` doesn't do the right thing. I'll look into addressing it there as well, but for now I'm using `ansi-str` which does the right thing. Would love a release if this looks good to you. 🙏
