### ISSUE TITLE
Table with dynamic columns

### ISSUE THREAD

**Issue by danieleades** [Nukesor/comfy-table#14]
I'd like to print a large table of data. There are more fields (columns) in the data than can be reasonably displayed, and the user should be able to choose which columns to display.

This is a little tricky, given that tables in this library are built exclusively from *rows*. How would you do this idiomatically using this library?

This would trivial to solve by *either*
- building a table by columns
- specifying columns which should be 'hidden' in the printed output

**Comment by Nukesor** [comment]
In an early version of Comfy-table, there was an additional `ColumnConstraint` named `Hidden`.
It has been removed though, since this can be also done programatically by manipulating the input-data itself.
On the other hand, I see how this can be handy and remove a lot of unnecessary data-manipulation code.

Building a table by columns however seems kind of unintuitive, at least it does to me.
Usually, the columns define the structure of the data (headers etc.) and the amount of columns is fix in a specific scope.
The amount of related data entries however is highly variable.

In most cases, it's more practical to add related data-sets (rows) one-by-one, instead of going trough all sets, sorting them by column and then add the columns. 

I guess the old `Hidden` constraint can be added again. This would allow the behavior described by you :)

The implementation of this is probably going to be a little tricky.
The formatting code is split into three parts:

1. `src/utils/arrangement.rs` Here we calculate which column get's how much screen space.
2 .`src/utils/format.rs` This actually formats the Cell's content, splits content that's too long with newlines and applies padding and other stuff.
3. `src/utils/borders.rs` That code is solely for drawing the table's borders.

Hidden columns will definitely need to be handled in the arrangement and formatting code.
I'm not exactly sure about the border drawing code, but it might be necessary in there as well.

You can start coding, if you're interested in building this yourself :)
I'm not exactly sure, if I'll find time to do this myself, since I don't need it for any of my projects right now.

**Comment by danieleades** [comment]
i appreciate the explanation. A 'Hidden' constraint would solve my problem. With a constraint I can easily apply a user-configurable filter to the displayed columns. Without such a filter I would need to reconstruct the table by checking each cell against the user-supplied column filters as I went. completely do-able, but very ugly.

I get that this library is more geared to display than data manipulation. Perhaps you're right to not include functionality like this. What i really need is a pandas-type library.

```rust
use hypothetical_pandas_clone::DataTable;

let data_table = DataTable::from(my_data);

/*
column filtering logic
*/

let display_table = comfytable::Table::from(data_table);
println!("{}", display_table)
```

**Comment by Nukesor** [comment]
Well, I couldn't resist and implemented the new Constraint:
https://github.com/Nukesor/comfy-table/pull/15

I tried to already test is thoroughly, but I'll probably add one or two additional tests before this will be merged to master.
Feel free to work with this branch until then :)

**Comment by Nukesor** [comment]
New version with the `hidden` constraint is published :)
