### ISSUE TITLE
Make `Color` (de)serializable

### ISSUE THREAD

**Issue by soywod** [Nukesor/comfy-table#150]
### A detailed description of the feature you would like to see added.

It could be nice to add a cargo feature `serde` or `derive` that enables (de)serialization of main structs and enums. The [`Color`](https://github.com/crossterm-rs/crossterm/blob/b056370038416584746fd59f7576ecd218b29f8d/src/style/types/color.rs#L220-L336) enum from `crossterm` already handles (de)serialization behind a cargo feature.

### Explain your usecase of the requested feature

Make your table customizable from user config files.

### Alternatives

An alternative could be to implement `From<crossterm::Color> for Color` and change the signature of few functions like `Cell::fg`. Instead of taking a `Color`, they could take a `impl Into<Color>`.

**Comment by Nukesor** [comment]
You should actually be able to achieve the alternative behavior with [this feature flag](https://github.com/Nukesor/comfy-table?tab=readme-ov-file#reexport_crossterm-disabled). However, the problem with this is that you may not use crossterm's  types when interacting with comfy-table, as this would otherwise result in a ABI incompatibility when you're updating `crossterm` in your own crate.
This has already lead to some issues in the past, which the crossterm types are no longer re-exported by default.



Regarding the original proposal, I guess this wouldn't be too much work. I'm just unsure how to name that feature flag though. `serde`/`derive` is a bit vague, since this is just about Colors/Attributes. People would probably assume that it allows data structures to be serialized/deserialized into tables, which really isn't something I want to get started with.

**Comment by Nukesor** [comment]
As a compromise, I guess it could already be enough to implement FromString?
https://tidelabs.github.io/tidext/strum/derive.EnumString.html#example-howto-use-enumstring

This would allow a simple `.into()` call from a string in your codebase. It wouldn't allow custom RGB or ANSI stuff though.

**Comment by soywod** [comment]
> You should actually be able to achieve the alternative behavior with [this feature flag](https://github.com/Nukesor/comfy-table?tab=readme-ov-file#reexport_crossterm-disabled). However, the problem with this is that you will run into issues when your own crossterm's types interact with comfy-table, as this will result in a ABI incompatibilities when you're updating `crossterm` in your own crate (or vice versa).

Indeed, this is a common issue with type sharing. I understand better the choice behind a dedicated `Color` struct.

> Regarding the original proposal, I guess this wouldn't be too much work. I'm just unsure how to name that feature flag though. `serde`/`derive` is a bit vague, since this is just about Colors/Attributes. People would probably assume that it allows data structures to be serialized/deserialized into tables, which really isn't something I want to get started with.

I did not think about it, it can definitely lead to confusion. 

> As a compromise, I guess it could already be enough to implement FromString?

But then you discard custom RGB and ANSI.

I guess the simplest is to make my own enum and implement my own (de)serializer (`&str` to basic colors, `u8` to ANSI and `(u8, u8, u8)` to RGB). I will close this issue and share the implementation here for those who are interested in.

**Comment by soywod** [comment]
In fact I just use internally `crossterm::style::Color` (with the `serde` feature, so it already handles the (de)serialization for me) and a mapper `fn(crossterm::style::Color) -> comfy_table::Color`.
