### ISSUE TITLE
Compact mode to remove empty areas?

### ISSUE THREAD

**Issue by sefeng211** [Nukesor/comfy-table#16]
Thanks for making this great library! 

One thing I noticed is that the generated tables have a lot of empty areas between the text and the border. 

I wonder if there's a plan to implement a compact mode to remove those empty areas as much as possible?

**Comment by Nukesor** [comment]
You're welcome :)

There's no such feature planned yet. However, this is definitely something that would fit in the scope of this project :).

One other thing that was planned is to allow custom delimiters, so we can split content not only by space.

A custom delimiter shouldn't be too hard, and it would also allow for a hacky solution to your problem (just take some weird delimiter nobody uses).

**Comment by Nukesor** [comment]
```
+----------+--------+----------+
| smol     | Header | Header3  |
|          | 2      |          |
+==============================+
| smol     | This   | This is  |
|          | is ano | the      | <--- These spaces.
|          | ther   | third    | <--- I.e. the next word doesn't fit into the current line
|          | text   | text     | <--- and is thereby shifted into the next line.
|----------+--------+----------|
| smol     | Now    | This is  |
|          | add    | awesome  |
|          | some   |          |
|          | multi  |          |
|          | line   |          |
|          | stuff  |          |
+----------+--------+----------+";
```

**Comment by sefeng211** [comment]
Not sure if we are talking about the same thing. Mabye...? I meant to say those circled areas in the picture. 
 
![comfy_table_empty](https://user-images.githubusercontent.com/8703745/100486404-b7824c80-30d1-11eb-960f-81a5fa6762b1.png)

**Comment by Nukesor** [comment]
Ahhh :D
Nope, that's not possible :D

This is due to the nature of terminals.
Terminals use a mono-space font. The only solution would be to completely remove the borders.

You would need a terminal, which is capable of differentiating between various characters and drawing them in a different way.

A GPU-Rendered terminal such as Alacritty might be capable of such a thing, but I'm not sure about this either.


Anyway, I'm closing this issue, since this is nothing Comfy-Table can solve :)
