### ISSUE TITLE
Trimming trailing whitespace in borderless tables

### ISSUE THREAD

**Issue by Ch00k** [Nukesor/comfy-table#20]
I am using comfy-table to build tables without borders. It all works great until I start to unnittest my tables. In my unit tests I am comparing the tables' String representations, with the expected result stored in a file (which I read with `include_str!`). Because my editor is configured to trim trailing whitespace on save, the expected result file does not have them, but the generated table does. So in order to do the comparison I first need to trim all trailing whitespace from the generated table, which I find a little cumbersome and annoying.

[This](https://github.com/Nukesor/comfy-table/blob/33739f9d7fe238c116801d86ffbaafe18b76dde4/tests/presets_test.rs#L20) test illustrate what I mean. In my opinion all whitespace between `3` and `\n` should be gone.

Now, I do realize that this is a "problem" of my editor, and others would likely never encounter it. However I would still like to suggest trimming trailing whitespace from borderless tables, just because trailing whitespace is usually useless.

I would be more than happy to make a PR, but wanted to first double-check if such a change would be OK.

**Comment by Nukesor** [comment]
Hm,

I see how this can be annoying :D

As a matter of fact, I ran into the same issue, but solved it by using a different way of string concatenation:
Here's an example in comfy-tables tests:
```
#[test]
fn utf8_no_borders() {
    let mut table = get_preset_table();
    table.load_preset(UTF8_NO_BORDERS);
    let expected = concat!(
        " Header1 ┆ Header2 ┆ Header3   \n",
        "═════════╪═════════╪═══════════\n",
        " One One ┆ One Two ┆ One Three \n",
        "╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌\n",
        " One One ┆ One Two ┆ One Three ",
    );
    println!("{}", table.to_string());
    assert_eq!(&table.to_string(), expected);
}
```

I would be fine with not filling up remaining space in the last column, if  there's no right border.
However, there are a few things/edge-cases we have to consider:

1. All of the white-space-filling code is in [this file](https://github.com/Nukesor/comfy-table/blob/master/src/utils/format.rs#L161). 
    Until now, the whole table "rendering" process has been cut into three parts:
    - Arrangement (determine which column gets how much space
    - Formatting (split the content, so it fits into the previously determined arrangement)
    - Border drawing (Draw the borders)
   
   This new logic would be the first, that connects two of those, namely formatting and border drawing.
   It's nothing super critical, but something we should keep in mind, since this is the begin of another layer of complexity.
2. We have to consider, that columns can be [Hidden](https://github.com/Nukesor/comfy-table/blob/master/src/style/column.rs#L7).
    This can be annoying, since we have to double-check, if the current column really is the last column to be displayed.
3. I'm not sure, if this is going to cause problems, but it would be best to write a test and ensure that this works when using [Row::max_height](https://github.com/Nukesor/comfy-table/blob/master/src/row.rs#L73)


I think this could be a nice addition, however I'm curious how much additional logic will be needed to implement this.
It might be, that I'm overthinking this, though :sweat_smile: .

Anyway, feel free to start coding :)

This is definitely something worth being merged!

**Comment by Nukesor** [comment]
A hacky solution around this whole stuff could be to go through all lines after we're done with everything and simply remove all trailing spaces from the finished table...

I'm not sure if this is the cleanest solution, though. Feels kinda hacky :D

**Comment by Nukesor** [comment]
The more I think about it, the more I get the feeling that the "hacky" solution would actually be the best one.
I'll create a simple draft.
