### ISSUE TITLE
Nested tables

### ISSUE THREAD

**Issue by DianaNites** [Nukesor/comfy-table#5]
It'd be nice if tables could be conveniently nested/added to rows.

This is technically currently possible, but not reliable because of automatic padding and wrapping. No way to get the proper size for the nested table, which otherwise defaults to the full terminal width.

In my case I want the nested tables width to be the remaining terminal width, after any previous columns. The parent table column will properly fit the content without broken formatting then.

The code I came up with to get it working in limited cases is below. It will fail if the first column has a width of more than `22`(`30 - 8`).

<details>
  <summary>Rust code</summary>

```rust
let mut table = Table::new();
table.set_table_width(30); // Problems only appear when content overflows terminal width?
table.set_content_arrangement(ContentArrangement::Dynamic);
table.add_row(&["Hello", "World"]);
//
let mut nested = Table::new();
nested.set_content_arrangement(ContentArrangement::Dynamic);
nested.set_header(&["One", "Two", "Three"]);
nested.set_table_width(
    table.get_table_width().unwrap()
    - table.get_column(0).unwrap().get_max_content_width()
    // 6 Is how many characters, including padding, the first column borders take.
    // Plus 1 for our own padding, for a total of 7.
    - 8,
);
nested.add_row(&["Four", "Five", "Six"]);
table.add_row(&["Nested", &nested.to_string()]);
println!("{}", table);
```

</details>

Which (correctly) produces the following table

<details>
  <summary>Table</summary>

```
+--------+-------------------+
| Hello  | World             |
|--------+-------------------|
| Nested | +-----+----+----+ |
|        | | One | Tw | Th | |
|        | |     | o  | re | |
|        | |     |    | e  | |
|        | +===============+ |
|        | | Fou | Fi | Si | |
|        | | r   | ve | x  | |
|        | +-----+----+----+ |
+--------+-------------------+
```

</details>

<details>
<summary>Broken formatting Table when 7 is used</summary>

```
+--------+-------------------+
| Hello  | World             |
|--------+-------------------|
| Nested | +-----+-----+---- |
|        | +                 |
|        | | One | Two | Th  |
|        | |                 |
|        | |     |     | re  |
|        | |                 |
|        | |     |     | e   |
|        | |                 |
|        | +================ |
|        | +                 |
|        | | Fou | Fiv | Si  |
|        | |                 |
|        | | r   | e   | x   |
|        | |                 |
|        | +-----+-----+---- |
|        | +                 |
+--------+-------------------+
```

</details>

**Comment by Nukesor** [comment]
Nested tables, don't work out of the box yet :/

Integrating this should be possible, but is probably complex. Since we don't know the width of columns, we would have to create the table somewhere in the midst of the arrangement computation and insert it into the table afterwards.

To be honest, I didn't design the whole algorithm with nested tables in mind.

In Regard to your computation:
- 30 base length
- 6 column width. `.get_max_content_width()` only returns the actual content's width. Without padding. I added a comment to clarify this and an additional convenience method `get_max_width()`, which adds content_width + padding
- 3 Borders
- 2 columns with 2*1 padding each

=> 30 - 6 - 3 - 4 = 17

Your problem appears, because you call `get_max_content_width()` before you actually add the row that contains `Nested`. Because of this the function returns 5 (`Hello`) instead of 6 (`Nested`), which distorts the computation by the value of `1`.

**Comment by DianaNites** [comment]
That explains it, thanks! I'll have to keep an eye out for that, though thankfully not a problem in the real code.
