### ISSUE TITLE
Applying an underline only to the table heading, not the entire cell

### ISSUE THREAD

**Issue by david-perez** [Nukesor/comfy-table#54]
The following code:

```rust
let mut table = Table::new();
table.load_preset(comfy_table::presets::NOTHING);
table.set_header(vec![
    "A heading".bold(),
    "Column 1".bold(),
    "A slightly longer heading".bold(),
]);
for i in 0..5 {
    let row: Vec<_> = (0..3).map(|j| format!("Row {} col {}", i, j)).collect();
    table.add_row(row);
}
```

produces a table with misaligned headings.

![screenshot-211107-202200](https://user-images.githubusercontent.com/6341745/140658992-a11a3d06-432b-4260-a868-1c27b1053b9d.png)

If I coerce each row into a `Vec<StyledContent<String>>` by calling `.reset()` on the `String`s:

```rust
let mut table = Table::new();
table.load_preset(comfy_table::presets::NOTHING);
table.set_header(vec![
    "A heading".bold(),
    "Column 1".bold(),
    "A slightly longer heading".bold(),
]);
for i in 0..5 {
    let row: Vec<_> = (0..3)
        .map(|j| format!("Row {} col {}", i, j).reset()) // Change.
        .collect();
    table.add_row(row);
}
```

the problem goes away.

![screenshot-211107-202527](https://user-images.githubusercontent.com/6341745/140658993-2722d11d-346f-4f41-995d-983632922684.png)

**Comment by Nukesor** [comment]
What are those `.bold()` calls you're using. It looks like you're not using comfy-table's build in styling, but rather external tools? 

Please use the styling on the `Cell` type [link](https://docs.rs/comfy-table/5.0.0/comfy_table/struct.Cell.html#method.add_attribute). Otherwise things will break, as this library doesn't detect ANSI escape sequences from other libraries!

Take a look a the examples: https://github.com/Nukesor/comfy-table#more-features

**Comment by david-perez** [comment]
Ah, sorry, the calls to `.bold()` and `.reset()` come [from `crossterm`](https://docs.rs/crossterm/0.22.1/crossterm/style/trait.Stylize.html).

> Please use the styling on the Cell type link.

If I use `Cell`, an underline applies to the entire cell when I want it to apply to only the heading text.

This code:

```rust
let mut table = Table::new();
table.load_preset(comfy_table::presets::NOTHING);
table.set_header(vec![
    Cell::new("A heading").add_attribute(Attribute::Underlined),
    Cell::new("Column 1").add_attribute(Attribute::Underlined),
    Cell::new("A slightly longer heading").add_attribute(Attribute::Underlined),
]);

for i in 0..5 {
    let row: Vec<_> = (0..3)
        .map(|j| format!("Row {} col {}", i, j))
        .collect();
    table.add_row(row);
}
```

produces this:

![screenshot-211109-162527](https://user-images.githubusercontent.com/6341745/140953452-46ca4773-a137-4a5a-91e5-43698bce39b4.png)

If I use `.underlined()` and `.reset()` from `crossterm` as in my second code listing in my comment above, I get what I'm looking after:

![screenshot-211109-162755](https://user-images.githubusercontent.com/6341745/140953457-bece450e-763d-4081-ab8d-cfbf1b53cb01.png)

I totally understand that using ANSI escape sequences from other libraries is incompatible with `comfy-table`. Is there a way of achieving what I'm looking after entirely within `comfy-table`? I've updated the issue title. Thanks.

**Comment by Nukesor** [comment]
I guess this can be seen as a bug?

Right now, the style is always applied to the whole line, but it makes indeed sense to only apply it to the text, while ignoring any spaces.

However, I'm not sure if this can be considered a breaking change. I'm thinking if this is expected behavior for some people out there. In case it is, we would have to make this configurable.

**Comment by Nukesor** [comment]
@david-perez Please check the PR, whether this suits your needs :)
