### ISSUE TITLE
Avoiding wrapping contents

### ISSUE THREAD

**Issue by casey** [Nukesor/comfy-table#66]
I think I must be missing something, but I can't figure out how to prevent the contents of cells from wrapping.

Here's my code:

```
    let mut table = comfy_table::Table::new();
    table.set_table_width(100);

    table.set_header(&["", "redb", "lmdb", "sled"]);

    for (benchmark, _duration) in &redb_results {
        table.add_row(&[benchmark]);
    }

    for results in [redb_results, lmdb_results, sled_results] {
        for (i, (_benchmark, duration)) in results.iter().enumerate() {
            table
                .get_row_mut(i)
                .unwrap()
                .add_cell(comfy_table::Cell::new(format!(
                    "{}ms",
                    duration.as_millis()
                )));
        }
    }

    println!("{table}");
```

And here's the table it prints:

```
+--------------------+------+------+------+
|                    | redb | lmdb | sled |
+=========================================+
| bulk load          | 4136 | 1235 | 1428 |
|                    | ms   | ms   | 2ms  |
|--------------------+------+------+------|
| individual writes  | 50ms | 10ms | 3547 |
|                    |      |      | ms   |
|--------------------+------+------+------|
| batch writes       | 5495 | 3010 | 1126 |
|                    | ms   | ms   | 8ms  |
|--------------------+------+------+------|
| random reads       | 1106 | 1108 | 1703 |
|                    | ms   | ms   | ms   |
|--------------------+------+------+------|
| random reads       | 926m | 1104 | 1518 |
|                    | s    | ms   | ms   |
|--------------------+------+------+------|
| random reads       | 993m | 1219 | 1495 |
|                    | s    | ms   | ms   |
|--------------------+------+------+------|
| random range reads | 1137 | 1481 | 2264 |
|                    | ms   | ms   | ms   |
|--------------------+------+------+------|
| random range reads | 1144 | 1461 | 2317 |
|                    | ms   | ms   | ms   |
|--------------------+------+------+------|
| random range reads | 1154 | 1422 | 2169 |
|                    | ms   | ms   | ms   |
|--------------------+------+------+------|
| removals           | 2677 | 1004 | 2824 |
|                    | ms   | ms   | ms   |
+--------------------+------+------+------+
```

I'd like the table to be wider to avoid wrapping the content of any of the cells. Is there a way to do this?

**Comment by Nukesor** [comment]
Damn, you found a bug.

I'm currently recalculating the max-width of each column everytime a new row is added.
This is useful as users might want to know how wide which column is, so they can add manual constraints without depending on comfy-table's internal content arrangement.

This max-width is then also used to run the first round of calculations for the target-width of each Cell.
People usually create the Rows in one go instead of adding rows and adding individual rows to them lateron :sweat_smile:. That's why this didn't pop up yet.

The table can't know that the content width of a Column should be should be re-calculated if Cells are added to a mutable reference of a Row.
This is a design flaw and we should definitely calculate the content width on-the-fly in the future, whenever the user or the library requests it.

I guess this should be a relatively easy fix, but I want to take the time to properly write a regression test for this. I'll probably find time to do this tomorrow.

Until then, a fix would probably be to create the finished rows in one go.

**Comment by casey** [comment]
I'm happy to have found a bug, as opposed to have missed something embarrassingly obvious in the documentation 😅 Nice, glad I can work around it by instantiating finished rows.

**Comment by Nukesor** [comment]
I fixed the issue at hand, but discovered a whole new class of problems/bugs that I simply haven't considered until now :D

Once I'm confident that everything is in order, I'll merge the MR and release a new major version :)

**Comment by casey** [comment]
Nice!
