### ISSUE TITLE
Syntax highlighting for in-table code snippets

### ISSUE THREAD

**Issue by Rudo2204** [Nukesor/comfy-table#9]
Is there any easy way that I can use [bat (library)](https://docs.rs/bat/0.15.4/bat/) to render output of the table?
This would greatly improve the aesthetic of the output and may even make the library way more ergonomic.

**Comment by Rudo2204** [comment]
It seems like [`bat` doesn't implement `std::fmt` trait for `PrettyPrinter::print` yet](https://github.com/sharkdp/bat/issues/956).
It looks like integrating `bat` with `comfy-table` will take a lot of work!

**Comment by Nukesor** [comment]
Hi :)

To be honest, I don't quite understand what benefits would come from migrating/supporting bat. Could you give me a use-case, which shows the improvements given by bat?

**Comment by Rudo2204** [comment]
I think having syntax highlighting would be pretty cool.

**Comment by Nukesor** [comment]
Ahh ok :D

Didn't know you were specifically using this library for displaying code^^. Yep, I guess that could be pretty cool. A new flag on cells which results in the cell's content being processed by bat.

However, I see some problems with the dynamic content arrangement. Code in cells would have to be untouched. Otherwise unwanted new-lines could be inserted, which in turn break the syntax flow.

A solution to this would be to apply syntax highlighting before we break the content, but this would make the content arrangement a LOT harder. We would have to ignore/handle the ascii escape codes, which might be very hard to distinguish from actual code.

**Comment by Nukesor** [comment]
Closing for now, since this is pretty out-of-scope for now.
